---
# Плановые задания Nexus (в т.ч. бэкап из шаблона backup.groovy.j2).
- name: Define backup task if backup is configured
  ansible.builtin.set_fact:
    _nexus_backup_task:
      - name: db and blobstores backup
        typeId: script
        schedule_type: "{{ nexus_backup_schedule_type }}"
        cron: "{{ nexus_backup_cron }}"
        start_date_time: "{{ nexus_backup_start_date_time | default('') }}"
        weekly_days: "{{ nexus_backup_weekly_days | default([]) }}"
        monthly_days: "{{ nexus_backup_monthly_days | default([]) }}"
        taskProperties:
          language: groovy
          source: "{{ lookup('template', './templates/backup.groovy.j2') }}"
  when:
    - nexus_backup_configure | bool
    - not (nexus_sync_repositories_only | default(false) | bool)

- name: Create scheduled tasks (with backup task if relevant)
  ansible.builtin.include_tasks: create_task_each.yml
  with_items: "{{ nexus_scheduled_tasks + _nexus_backup_task | default([]) }}"
  when:
    - nexus_run_provisionning | default(true) | bool
    - not (nexus_sync_repositories_only | default(false) | bool)
