---
# Версия, установка, общие параметры инстанса (пароль админа лучше вынести в vault).
nexus_version: "3.90.2-06"
nexus_local_package_file: "nexus-{{ nexus_version }}-linux-x86_64.tar.gz"
nexus_install_dir_name: "nexus-{{ nexus_version }}"
nexus_admin_password: "nexus1234"
nexus_public_hostname: "nexus.btnxlocal.ru"
nexus_timezone: "UTC+3"
nexus_ldap_realm: false
nexus_docker_bearer_token_realm: true
nexus_npm_bearer_token_realm: false
